//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShopMobileApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartShopMobileApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply voucher.
        /// </summary>
        internal static string ApplyVoucher {
            get {
                return ResourceManager.GetString("ApplyVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card name:.
        /// </summary>
        internal static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number:.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart value:.
        /// </summary>
        internal static string CartValue {
            get {
                return ResourceManager.GetString("CartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred currency:.
        /// </summary>
        internal static string ChoosePreferredCurrency {
            get {
                return ResourceManager.GetString("ChoosePreferredCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred language:.
        /// </summary>
        internal static string ChoosePreferredLanguage {
            get {
                return ResourceManager.GetString("ChoosePreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your supermarket:.
        /// </summary>
        internal static string ChooseYourSupermarket {
            get {
                return ResourceManager.GetString("ChooseYourSupermarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current offers:.
        /// </summary>
        internal static string CurrentOffers {
            get {
                return ResourceManager.GetString("CurrentOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current voucher for.
        /// </summary>
        internal static string CurrentVoucherFor {
            get {
                return ResourceManager.GetString("CurrentVoucherFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration month:.
        /// </summary>
        internal static string ExpirationMonth {
            get {
                return ResourceManager.GetString("ExpirationMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration year:.
        /// </summary>
        internal static string ExpirationYear {
            get {
                return ResourceManager.GetString("ExpirationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, .
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum price:.
        /// </summary>
        internal static string MaximumPrice {
            get {
                return ResourceManager.GetString("MaximumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum price:.
        /// </summary>
        internal static string MinimumPrice {
            get {
                return ResourceManager.GetString("MinimumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process payment.
        /// </summary>
        internal static string ProcessPayment {
            get {
                return ResourceManager.GetString("ProcessPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products:.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity:.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a product....
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security number:.
        /// </summary>
        internal static string SecurityNumber {
            get {
                return ResourceManager.GetString("SecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a month:.
        /// </summary>
        internal static string SelectAMonth {
            get {
                return ResourceManager.GetString("SelectAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a year:.
        /// </summary>
        internal static string SelectAYear {
            get {
                return ResourceManager.GetString("SelectAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for shopping at our supermarket!.
        /// </summary>
        internal static string ThankYouForShoppingAtOurSupermarket {
            get {
                return ResourceManager.GetString("ThankYouForShoppingAtOurSupermarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View statistics.
        /// </summary>
        internal static string ViewStatistics {
            get {
                return ResourceManager.GetString("ViewStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher history:.
        /// </summary>
        internal static string VoucherHistory {
            get {
                return ResourceManager.GetString("VoucherHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current shopping cart:.
        /// </summary>
        internal static string YourCurrentShoppingCart {
            get {
                return ResourceManager.GetString("YourCurrentShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your latest shopping cart:.
        /// </summary>
        internal static string YourLatestShoppingCart {
            get {
                return ResourceManager.GetString("YourLatestShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shopping cart is empty!.
        /// </summary>
        internal static string YourShoppingCartIsEmpty {
            get {
                return ResourceManager.GetString("YourShoppingCartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spendings by categories:.
        /// </summary>
        internal static string YourSpendingsByCategories {
            get {
                return ResourceManager.GetString("YourSpendingsByCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spendings in the last 3 months:.
        /// </summary>
        internal static string YourSpendingsInTheLast3Months {
            get {
                return ResourceManager.GetString("YourSpendingsInTheLast3Months", resourceCulture);
            }
        }
    }
}
